config/routes.rb
Bookswapped::Application.routes.draw do

  scope '/' do
    get 'about'           => 'static#about'
    get 'advanced_search' => 'static#advanced_search'
    get 'contact'         => 'static#contact'
    get 'faq'             => 'static#faq'
  end

  resources :books do
    collection do
      get 'autocomplete_title'
      get 'search'
    end

    member do
      get 'offers'
    end
  end

  match '/books/:id/*title' => 'books#show', :as => :book_with_title

  root :to => "books#search"

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :isbn, :ean, :asin
  validates_uniqueness_of :ean

  serialize :authors

  def to_param
    "#{title.parameterize}"
  end

  def image
    Amazon::Image.new(asin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :set_body_class
  
  protect_from_forgery

  private

  def set_body_class
    @body_class = "#{params[:controller].parameterize}"
  end

  def find_book(ean)
    @book = Book.find_by_ean(ean)

    unless @book
      EM.synchrony do
        @book = Amazon::Book.find(ean)
        @book.save
        EM.stop
      end
    end

    @book
  end
  
  def find_offers
    @offers = Rails.cache.read("#{@book.ean}_offers")

    unless @offers
      parameters = {
        :ean  => @book.ean,
        :isbn => @book.isbn,
        :asin => @book.asin
      }

      @offers = MultiSearch::Offer.all(parameters)

      Rails.cache.write("#{@book.ean}_offers", @offers, :expires_in => 1.hour)
    end

    @offers
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def search
    @book_search = params[:book_search]
    @book_search ||= {}

    EM.synchrony do
      @books = Amazon::Book.all(@book_search)
      EM.stop
    end

    @books.map(&:save)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def offers
    find_book(params[:id])
    find_offers

    respond_to do |format|
      format.json do
        @offers = @offers[0..14]

        @offers.map! do |offer|
          {
            :vendor      => offer.vendor,
            :condition   => offer.condition,
            :price       => offer.price,
            :ship_rate   => offer.ship_rate,
            :total_price => offer.total_price,
            :link        => offer.link
          }
        end

        render json: @offers
      end
    end
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    find_book(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  respond_to :html
end

app/helpers/application_helper.rb
module ApplicationHelper

  def body_class
    @body_class
  end

end

app/helpers/books_helper.rb
module BooksHelper
  def book_image(book, options = {}, &block)
    image = (book.image).tap do |image|

      if options[:size]
        image.set_size!(options[:size])
      else
        image.set_size!(:medium)
      end

      yield image if block_given?
    end

    image_tag(image.url, :class => "book_image #{options[:size]}", :alt => "#{book.title} Cover")
  end

  def book_author(book)
    [book.authors].flatten.to_sentence
  end
end

app/views/books/_form.html.haml
= form_for @book do |f|
  -if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :isbn
    = f.text_field :isbn
  .field
    = f.label :ean
    = f.text_field :ean
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :authors
    = f.text_area :authors
  .field
    = f.label :edition
    = f.text_field :edition
  .field
    = f.label :cover
    = f.text_field :cover
  .field
    = f.label :publisher
    = f.text_field :publisher
  .field
    = f.label :pages
    = f.number_field :pages
  .field
    = f.label :publication_date
    = f.text_field :publication_date
  .field
    = f.label :asin
    = f.text_field :asin
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/books/_offers.html.haml
%table

  %thead
    %th.hide
    %th Vendor
    %th Condition
    %th Price
    %th Ship Rate
    %th Total Cost
    %th{:width => '125'} &hearts;

  %tbody
    - @offers.each do |offer|
      %tr.offer
        %td.hide= link_to('Select', offer.link)
        %td= offer.vendor
        %td= offer.condition
        %td= offer.price
        %td= offer.ship_rate
        %td= offer.total_price
        %td 
          %h3.arrow.hide &larr; Select This Offer

app/views/books/_search.html.haml
- if @books.empty?
  - unless @book_search == {}
    %h2 
      &hearts; Whoops... just can't seem to find what you are looking for. Why don't you try our
      = link_to 'Advanced Search', advanced_search_path
      ?
- else
  - @books.each do |book|
    .book{:class => "#{cycle('odd', 'even')}", :title => "Select #{book.title}"}
      .selected.grid_2.hide
        %h2 You selected:
      .hover.suffix_1
        %h3.arrow.hide &rarr;
      .image.grid_3.suffix_1
        = book_image(book, :size => :medium)
      .information.grid_10
        %h4= book.title
        %span by: #{book_author(book)} (#{book.publisher})
        %br/
        %span Published: #{book.publication_date}
        %br/
        %span Binding: #{book.cover}
        = hidden_field_tag(:ean, book.ean)
      

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/search.html.haml
%h2 Bookswapped.com is a textbook price-comparison engine designed to make buying textbooks simpler. Oh, did I mention it's less expensive? Well, it is.

%h2 Here's how it works:

#step_1.step
  = form_tag(search_books_path, :remote => true, :method => :get, :id => 'book_search_form') do

    .search
      %h2.left 1.) You search for a book:
      %span.left
        = text_field_tag('book_search[keywords]', @book_search[:keywords], :placeholder => 'type here to search', :size => 25, :class => 'hide')
        \.

  #step_1_loading.loading.hide
    %h2
      %img{:src => '/images/loading.gif', :width => 20}
      Give it a sec...

  #books
    = render :partial => 'search'

#step_2.step.hide
  %h2 2.) We compare the prices of every major online book vendor

  #step_2_loading.loading.hide
    %h2
      %img{:src => '/images/loading.gif', :width => 20}
      Comparing prices...

  %h2#completed.prefix_1.hide &rarr; Finished!

#step_3.step.hide
  %h2 3.) You select an offer:

  #offers
    %table#offers_table
      %thead
        %th Vendor
        %th Condition
        %th Price
        %th Ship Rate
        %th Total Cost
        %th{:width => '125'} &hearts;
      %tbody

%script{:id => 'offerRowTemplate', :type => 'text/x-jQuery-tmpl'}
  %tr.offer
    %td ${vendor}
    %td ${condition}
    %td ${price}
    %td ${ship_rate}
    %td ${total_price}
    %td.arrow.hide
      %h3
        %a{:href => '${link}'} &rarr; Select This Offer

app/views/books/search.js.haml
$(function() {
$("#step_1 .loading").hide();
$("#books").html("#{escape_javascript(render :partial => 'search')}");
$(window).load(function(){replaceNullImages()});
});

app/views/books/show.html.haml
- content_for :title, 'Textbook Price Comparison'

#step_1.step
  = form_tag(search_books_path, :remote => true, :method => :get, :id => 'book_search_form') do
    
    - @book_search ||= {}

    %h2 1.) You search for a book:
    = text_field_tag('book_search[keywords]', @book_search[:keywords], :placeholder => 'type here to search', :size => 20, :class => 'hide')

  .loading.hide
    %h2
      = image_tag('loading.gif', :width => 20, :style => 'padding-bottom:15px;')
      Give it a sec...

  #books

#step_2.step.hide
  %h2 2.) Our team of robots will search all the major online book vendors to find the lowest price available for your book.
  %h3{:style => 'font-family:"Nixie One"'}
    In the meanwhile, would you mind telling us how much you were going to pay?
  %h3{:style => 'font-family:"Nixie One"'}
    MSRP says: $
    = text_field_tag('msrp', '45.00', :size => 5)
    = link_to 'No, thanks', '#'
  .loading
    %h2
      = image_tag('loading.gif', :width => 20, :style => 'padding-bottom:15px;')
      Comparing prices...
  #offers.hide

#step_3.step.hide
  %h2 3.) You select which offer suits you best:

app/views/layouts/_menu.html.haml
%ul
  %li= link_to ':home', search_books_path
  %li= link_to ':about', about_path
  %li= link_to ':help', faq_path

app/views/layouts/application.html.haml
!!!
/[if lt IE 7]
  %html.no-js.ie6.oldie{:lang => 'en'}
/[if IE 7]
  %html.no-js.ie7.oldie{:lang => 'en'}
/[if IE 8]
  %html.no-js.ie8.oldie{:lang => 'en'}
/[if gt IE 8]
  %html.no-js{:lang => 'en'}

%head
  %meta{'charset' => 'utf-8'}
  %meta{'http-equiv' => 'X-UA-Compatible', 'content' => 'IE=edge,chrome=1'}
  %title Bookswapped.com - A Book Price Comparison Website
  %meta{'name' => 'description', 'content' => 'A textbook price comparison website.'}
  %meta{'name' => 'author', 'content' => 'Ryan Closner'}

  %meta{'property' => 'og:title', 'content' => 'SPUBooks.com - A textbook/book price comparison website.'}
  %meta{'property' => 'og:description', 'content' => 'A textbook/book price comparison website written by an SPU student, for SPU students.'}
  %meta{'property' => 'og:image', 'content' => 'http://ecx.images-amazon.com/images/P/0547167024.01._SCMZZZZZZZ_.jpg'}
  %meta{'property' => 'og:type', 'content' => 'book'}
  %meta{'property' => 'og:url', 'content' => 'http://spubooks.com'}

  = csrf_meta_tag

  %link{'rel' => 'dns-prefetch',  'href' => '//ajax.googleapis.com'}
  %link{'rel' => 'shortcut icon', 'href' => '/favicon.png'}
  %link{'rel' => 'apple-touch-icon.png', 'href' => '/apple-touch-icon.png'}
  %link{'rel' => 'stylesheet', 'href' => 'http://fonts.googleapis.com/css?family=Nixie+One|Dawning+of+a+New+Day|Open+Sans', 'type' => 'text/css'}

  = stylesheet_link_tag :application

%body{:class => body_class }
  #container.container_24
    %header#header
      #logo.left
        = link_to '/' do
          %h1{:title => 'Bookswapped.com'} Bookswapped.com
      #menu.right
        %nav= render :partial => 'layouts/menu'

    #main{:role => 'main'}
      = yield

  %script{:src => '//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js'}
  %script{:src => '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/jquery-ui.min.js'}
  :javascript
    window.jQuery || document.write("<script src='/assets/jquery-1.6.2.min.js'><\/script>")

  = javascript_include_tag :application

  :javascript
    var _gaq=[['_setAccount','UA-11498024-1'],['_trackPageview'],['_trackPageLoadTime']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));

  /[ if lt IE 7]
    %script{:src => '//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js'}
    %script window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})

= yield :after_load